{"nodes":[{"pos":[726,810],"content":"The exception that is thrown when authentication fails for an authentication stream.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when authentication fails for an authentication stream.","pos":[0,84]}]},{"pos":[822,1238],"content":"The <xref:System.Net.Security.NegotiateStream> and <xref:System.Net.Security.SslStream> classes throw this exception when the client or server cannot be authenticated. When this exception is thrown, you can retry the authentication with different credentials. If you cannot retry the authentication, a <xref:System.Security.Authentication.InvalidCredentialException> is thrown instead of the AuthenticationException.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"The <xref:System.Net.Security.NegotiateStream> and <xref:System.Net.Security.SslStream> classes throw this exception when the client or server cannot be authenticated. When this exception is thrown, you can retry the authentication with different credentials. If you cannot retry the authentication, a <xref:System.Security.Authentication.InvalidCredentialException> is thrown instead of the AuthenticationException.","pos":[0,416],"nodes":[{"content":"The &lt;xref:System.Net.Security.NegotiateStream&gt; and &lt;xref:System.Net.Security.SslStream&gt; classes throw this exception when the client or server cannot be authenticated.","pos":[0,167],"source":"The <xref:System.Net.Security.NegotiateStream> and <xref:System.Net.Security.SslStream> classes throw this exception when the client or server cannot be authenticated."},{"content":"When this exception is thrown, you can retry the authentication with different credentials.","pos":[168,259]},{"content":"If you cannot retry the authentication, a &lt;xref:System.Security.Authentication.InvalidCredentialException&gt; is thrown instead of the AuthenticationException.","pos":[260,416],"source":" If you cannot retry the authentication, a <xref:System.Security.Authentication.InvalidCredentialException> is thrown instead of the AuthenticationException."}]}]},{"pos":[2007,2139],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Security.Authentication.AuthenticationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with no message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with no message."},{"pos":[2151,2181],"content":"This constructor does nothing.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor does nothing.","pos":[0,30]}]},{"pos":[2881,3024],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Security.Authentication.AuthenticationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with the specified message."},{"pos":[3036,3227],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter. The <xref:System.Exception.InnerException%2A> property is set to `null`.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id=\"ph1\">`message`</ph> parameter.","pos":[0,118],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property is set to <ph id=\"ph1\">`null`</ph>.","pos":[119,191],"source":" The <xref:System.Exception.InnerException%2A> property is set to `null`."}]},{"pos":[3379,3444],"content":"A <xref:System.String> that describes the authentication failure.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the authentication failure.","pos":[0,65],"source":"A <xref:System.String> that describes the authentication failure."}]},{"pos":[4309,4594],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Security.Authentication.AuthenticationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class from the specified instances of the <bpt id=\"p2\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> and &lt;xref:System.Runtime.Serialization.StreamingContext&gt; classes.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class from the specified instances of the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> and <xref:System.Runtime.Serialization.StreamingContext> classes."},{"pos":[4906,5132],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> instance that contains the information required to deserialize the new <bpt id=\"p2\">&lt;xref href=\"System.Security.Authentication.AuthenticationException\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> instance.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> instance that contains the information required to deserialize the new <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> instance."},{"pos":[5237,5301],"content":"A <xref:System.Runtime.Serialization.StreamingContext> instance.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; instance.","pos":[0,64],"source":"A <xref:System.Runtime.Serialization.StreamingContext> instance."}]},{"pos":[5988,6151],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Security.Authentication.AuthenticationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message and inner exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with the specified message and inner exception."},{"pos":[6163,6394],"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id=\"ph1\">`message`</ph> parameter and initializes the &lt;xref:System.Exception.InnerException%2A&gt; property with the <ph id=\"ph2\">`innerException`</ph> parameter value.","needQuote":true,"needEscape":true,"extradata":"MT","source":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter and initializes the <xref:System.Exception.InnerException%2A> property with the `innerException` parameter value."},{"pos":[6572,6637],"content":"A <xref:System.String> that describes the authentication failure.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the authentication failure.","pos":[0,65],"source":"A <xref:System.String> that describes the authentication failure."}]},{"pos":[6711,6782],"content":"The <xref:System.Exception> that is the cause of the current exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Exception&gt; that is the cause of the current exception.","pos":[0,71],"source":"The <xref:System.Exception> that is the cause of the current exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Security.Authentication.AuthenticationException\n  id: AuthenticationException\n  children:\n  - System.Security.Authentication.AuthenticationException.#ctor\n  - System.Security.Authentication.AuthenticationException.#ctor(System.String)\n  - System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: AuthenticationException\n  nameWithType: AuthenticationException\n  fullName: System.Security.Authentication.AuthenticationException\n  type: Class\n  summary: The exception that is thrown when authentication fails for an authentication stream.\n  remarks: The <xref:System.Net.Security.NegotiateStream> and <xref:System.Net.Security.SslStream> classes throw this exception when the client or server cannot be authenticated. When this exception is thrown, you can retry the authentication with different credentials. If you cannot retry the authentication, a <xref:System.Security.Authentication.InvalidCredentialException> is thrown instead of the AuthenticationException.\n  example:\n  - <xref:System.Net.Security.NegotiateStream> &#124; <xref:System.Net.Security.SslStream>\n  syntax:\n    content: 'public class AuthenticationException : SystemException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Security.Authentication.AuthenticationException.#ctor\n  id: '#ctor'\n  parent: System.Security.Authentication.AuthenticationException\n  langs:\n  - csharp\n  name: AuthenticationException()\n  nameWithType: AuthenticationException.AuthenticationException()\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Security.Authentication\n  summary: Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with no message.\n  remarks: This constructor does nothing.\n  syntax:\n    content: public AuthenticationException ();\n    parameters: []\n  overload: System.Security.Authentication.AuthenticationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Security.Authentication.AuthenticationException\n  langs:\n  - csharp\n  name: AuthenticationException(String)\n  nameWithType: AuthenticationException.AuthenticationException(String)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Security.Authentication\n  summary: Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with the specified message.\n  remarks: This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter. The <xref:System.Exception.InnerException%2A> property is set to `null`.\n  syntax:\n    content: public AuthenticationException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the authentication failure.\n  overload: System.Security.Authentication.AuthenticationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Security.Authentication.AuthenticationException\n  langs:\n  - csharp\n  name: AuthenticationException(SerializationInfo,StreamingContext)\n  nameWithType: AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Security.Authentication\n  summary: Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class from the specified instances of the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> and <xref:System.Runtime.Serialization.StreamingContext> classes.\n  syntax:\n    content: protected AuthenticationException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);\n    parameters:\n    - id: serializationInfo\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> instance that contains the information required to deserialize the new <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> instance.\n    - id: streamingContext\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref:System.Runtime.Serialization.StreamingContext> instance.\n  overload: System.Security.Authentication.AuthenticationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Security.Authentication.AuthenticationException\n  langs:\n  - csharp\n  name: AuthenticationException(String,Exception)\n  nameWithType: AuthenticationException.AuthenticationException(String,Exception)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Security.Authentication\n  summary: Initializes a new instance of the <xref href=\"System.Security.Authentication.AuthenticationException\"></xref> class with the specified message and inner exception.\n  remarks: This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter and initializes the <xref:System.Exception.InnerException%2A> property with the `innerException` parameter value.\n  syntax:\n    content: public AuthenticationException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the authentication failure.\n    - id: innerException\n      type: System.Exception\n      description: The <xref:System.Exception> that is the cause of the current exception.\n  overload: System.Security.Authentication.AuthenticationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n- uid: System.Security.Authentication.AuthenticationException.#ctor\n  parent: System.Security.Authentication.AuthenticationException\n  isExternal: false\n  name: AuthenticationException()\n  nameWithType: AuthenticationException.AuthenticationException()\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)\n  parent: System.Security.Authentication.AuthenticationException\n  isExternal: false\n  name: AuthenticationException(String)\n  nameWithType: AuthenticationException.AuthenticationException(String)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Security.Authentication.AuthenticationException\n  isExternal: false\n  name: AuthenticationException(SerializationInfo,StreamingContext)\n  nameWithType: AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)\n  parent: System.Security.Authentication.AuthenticationException\n  isExternal: false\n  name: AuthenticationException(String,Exception)\n  nameWithType: AuthenticationException.AuthenticationException(String,Exception)\n  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Security.Authentication.AuthenticationException.#ctor*\n  parent: System.Security.Authentication.AuthenticationException\n  isExternal: false\n  name: AuthenticationException\n  nameWithType: AuthenticationException.AuthenticationException\n"}