{"nodes":[{"pos":[1090,1166],"content":"The exception that occurs when code attempts to access a canceled print job.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that occurs when code attempts to access a canceled print job.","pos":[0,76]}]},{"pos":[1179,1959],"content":"If you are creating a [!INCLUDE[TLA#tla_winclient](~/add/includes/ajax-current-ext-md.md)] application that includes printing functionality and allows print jobs to be canceled, be sure to correctly handle this exception. An unhandled exception of this type can cause a Windows Presentation Foundation application to stop responding.      > [!CAUTION] >  Classes within the <xref:System.Printing> namespace are not supported for use within a Windows service or ASP.NET application or service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions.       If you want to print from a Windows Forms application, see the <xref:System.Drawing.Printing> namespace.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"If you are creating a <ph id=\"ph1\">[!INCLUDE[TLA#tla_winclient](~/add/includes/ajax-current-ext-md.md)]</ph> application that includes printing functionality and allows print jobs to be canceled, be sure to correctly handle this exception.","pos":[0,221],"source":"If you are creating a [!INCLUDE[TLA#tla_winclient](~/add/includes/ajax-current-ext-md.md)] application that includes printing functionality and allows print jobs to be canceled, be sure to correctly handle this exception."},{"content":"An unhandled exception of this type can cause a Windows Presentation Foundation application to stop responding.","pos":[222,333]},{"content":"&gt; <ph id=\"ph1\">[!CAUTION]</ph> &gt;  Classes within the &lt;xref:System.Printing&gt; namespace are not supported for use within a Windows service or ASP.NET application or service.","pos":[339,492],"source":"      > [!CAUTION] >  Classes within the <xref:System.Printing> namespace are not supported for use within a Windows service or ASP.NET application or service."},{"content":"Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions.","pos":[493,664]},{"content":"If you want to print from a Windows Forms application, see the &lt;xref:System.Drawing.Printing&gt; namespace.","pos":[671,775],"source":"       If you want to print from a Windows Forms application, see the <xref:System.Drawing.Printing> namespace."}]},{"pos":[2974,3077],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class."},{"pos":[3728,3872],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides a specific error condition.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error condition."},{"pos":[4026,4084],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[4700,4859],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides a specific error code and error condition.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code and error condition."},{"pos":[5029,5152],"content":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"An &lt;xref:System.Int32&gt; that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","pos":[0,123],"source":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception."}]},{"pos":[5216,5274],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[6088,6370],"content":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides specific <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> and <xref:System.Runtime.Serialization.StreamingContext>. This constructor is protected.","needQuote":true,"needEscape":true,"nodes":[{"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides specific <bpt id=\"p2\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> and &lt;xref:System.Runtime.Serialization.StreamingContext&gt;.","pos":[0,251],"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides specific <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> and <xref:System.Runtime.Serialization.StreamingContext>."},{"content":"This constructor is protected.","pos":[252,282]}]},{"pos":[6649,6713],"content":"The data that is required to serialize or deserialize an object.","needQuote":true,"needEscape":true,"nodes":[{"content":"The data that is required to serialize or deserialize an object.","pos":[0,64]}]},{"pos":[6809,6881],"content":"The context, including source and destination, of the serialized stream.","needQuote":true,"needEscape":true,"nodes":[{"content":"The context, including source and destination, of the serialized stream.","pos":[0,72]}]},{"pos":[7517,7710],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides a specific error condition, including the underlying cause of the exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error condition, including the underlying cause of the exception."},{"pos":[7890,7948],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[8022,8132],"content":"The underlying error condition that caused the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"The underlying error condition that caused the <xref href=\"System.Printing.PrintingCanceledException\"></xref>."},{"pos":[8812,9020],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides a specific error code and error condition, including the underlying cause of the exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code and error condition, including the underlying cause of the exception."},{"pos":[9216,9339],"content":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"An &lt;xref:System.Int32&gt; that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","pos":[0,123],"source":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception."}]},{"pos":[9403,9461],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[9535,9645],"content":"The underlying error condition that caused the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"The underlying error condition that caused the <xref href=\"System.Printing.PrintingCanceledException\"></xref>."},{"pos":[10403,10599],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that provides a specific error code, error condition, print queue name, job name, and job ID.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code, error condition, print queue name, job name, and job ID."},{"pos":[10819,10942],"content":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"An &lt;xref:System.Int32&gt; that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","pos":[0,123],"source":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception."}]},{"pos":[11006,11064],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[11135,11211],"content":"The name of the print queue hosting the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The name of the print queue hosting the print job that caused the exception.","pos":[0,76]}]},{"pos":[11275,11327],"content":"The name of the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The name of the print job that caused the exception.","pos":[0,52]}]},{"pos":[11388,11445],"content":"The ID number of the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The ID number of the print job that caused the exception.","pos":[0,57]}]},{"pos":[12267,12489],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Printing.PrintingCanceledException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specific error code, error condition, print queue name, job name, job ID, and underlying cause of the exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class with a specific error code, error condition, print queue name, job name, job ID, and underlying cause of the exception."},{"pos":[12735,12858],"content":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"An &lt;xref:System.Int32&gt; that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.","pos":[0,123],"source":"An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception."}]},{"pos":[12922,12980],"content":"A <xref:System.String> that describes the error condition.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error condition.","pos":[0,58],"source":"A <xref:System.String> that describes the error condition."}]},{"pos":[13051,13127],"content":"The name of the print queue hosting the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The name of the print queue hosting the print job that caused the exception.","pos":[0,76]}]},{"pos":[13191,13243],"content":"The name of the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The name of the print job that caused the exception.","pos":[0,52]}]},{"pos":[13304,13361],"content":"The ID number of the print job that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The ID number of the print job that caused the exception.","pos":[0,57]}]},{"pos":[13435,13473],"content":"The underlying cause of the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The underlying cause of the exception.","pos":[0,38]}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Printing.PrintingCanceledException\n  id: PrintingCanceledException\n  children:\n  - System.Printing.PrintingCanceledException.#ctor\n  - System.Printing.PrintingCanceledException.#ctor(System.String)\n  - System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String)\n  - System.Printing.PrintingCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Printing.PrintingCanceledException.#ctor(System.String,System.Exception)\n  - System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.Exception)\n  - System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32)\n  - System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32,System.Exception)\n  langs:\n  - csharp\n  name: PrintingCanceledException\n  nameWithType: PrintingCanceledException\n  fullName: System.Printing.PrintingCanceledException\n  type: Class\n  summary: The exception that occurs when code attempts to access a canceled print job.\n  remarks: \"If you are creating a [!INCLUDE[TLA#tla_winclient](~/add/includes/ajax-current-ext-md.md)] application that includes printing functionality and allows print jobs to be canceled, be sure to correctly handle this exception. An unhandled exception of this type can cause a Windows Presentation Foundation application to stop responding.  \\n  \\n> [!CAUTION]\\n>  Classes within the <xref:System.Printing> namespace are not supported for use within a Windows service or ASP.NET application or service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions.  \\n  \\n If you want to print from a Windows Forms application, see the <xref:System.Drawing.Printing> namespace.\"\n  syntax:\n    content: 'public class PrintingCanceledException : System.Printing.PrintJobException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  - System.Printing.PrintSystemException\n  - System.Printing.PrintJobException\n  implements: []\n  inheritedMembers:\n  - System.Printing.PrintJobException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Printing.PrintJobException.JobId\n  - System.Printing.PrintJobException.JobName\n  - System.Printing.PrintJobException.PrintQueueName\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor\n  id: '#ctor'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException()\n  nameWithType: PrintingCanceledException.PrintingCanceledException()\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException()\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class.\n  syntax:\n    content: public PrintingCanceledException ();\n    parameters: []\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(String)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(String)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(String)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error condition.\n  syntax:\n    content: public PrintingCanceledException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String)\n  id: '#ctor(System.Int32,System.String)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(Int32,String)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code and error condition.\n  syntax:\n    content: public PrintingCanceledException (int errorCode, string message);\n    parameters:\n    - id: errorCode\n      type: System.Int32\n      description: An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(SerializationInfo,StreamingContext)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(SerializationInfo,StreamingContext)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides specific <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> and <xref:System.Runtime.Serialization.StreamingContext>. This constructor is protected.\n  syntax:\n    content: protected PrintingCanceledException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The data that is required to serialize or deserialize an object.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The context, including source and destination, of the serialized stream.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(String,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(String,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(String,Exception)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error condition, including the underlying cause of the exception.\n  syntax:\n    content: public PrintingCanceledException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n    - id: innerException\n      type: System.Exception\n      description: The underlying error condition that caused the <xref href=\"System.Printing.PrintingCanceledException\"></xref>.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.Exception)\n  id: '#ctor(System.Int32,System.String,System.Exception)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(Int32,String,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,Exception)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code and error condition, including the underlying cause of the exception.\n  syntax:\n    content: public PrintingCanceledException (int errorCode, string message, Exception innerException);\n    parameters:\n    - id: errorCode\n      type: System.Int32\n      description: An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n    - id: innerException\n      type: System.Exception\n      description: The underlying error condition that caused the <xref href=\"System.Printing.PrintingCanceledException\"></xref>.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32)\n  id: '#ctor(System.Int32,System.String,System.String,System.String,System.Int32)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(Int32,String,String,String,Int32)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class that provides a specific error code, error condition, print queue name, job name, and job ID.\n  syntax:\n    content: public PrintingCanceledException (int errorCode, string message, string printQueueName, string jobName, int jobId);\n    parameters:\n    - id: errorCode\n      type: System.Int32\n      description: An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n    - id: printQueueName\n      type: System.String\n      description: The name of the print queue hosting the print job that caused the exception.\n    - id: jobName\n      type: System.String\n      description: The name of the print job that caused the exception.\n    - id: jobId\n      type: System.Int32\n      description: The ID number of the print job that caused the exception.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32,System.Exception)\n  id: '#ctor(System.Int32,System.String,System.String,System.String,System.Int32,System.Exception)'\n  parent: System.Printing.PrintingCanceledException\n  langs:\n  - csharp\n  name: PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n  type: Constructor\n  assemblies:\n  - ReachFramework\n  namespace: System.Printing\n  summary: Initializes a new instance of the <xref href=\"System.Printing.PrintingCanceledException\"></xref> class with a specific error code, error condition, print queue name, job name, job ID, and underlying cause of the exception.\n  syntax:\n    content: public PrintingCanceledException (int errorCode, string message, string printQueueName, string jobName, int jobId, Exception innerException);\n    parameters:\n    - id: errorCode\n      type: System.Int32\n      description: An <xref:System.Int32> that is interpreted as an HRESULT, a coded numerical value that is assigned to a specific exception.\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error condition.\n    - id: printQueueName\n      type: System.String\n      description: The name of the print queue hosting the print job that caused the exception.\n    - id: jobName\n      type: System.String\n      description: The name of the print job that caused the exception.\n    - id: jobId\n      type: System.Int32\n      description: The ID number of the print job that caused the exception.\n    - id: innerException\n      type: System.Exception\n      description: The underlying cause of the exception.\n  overload: System.Printing.PrintingCanceledException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Printing.PrintJobException\n  isExternal: false\n  name: System.Printing.PrintJobException\n- uid: System.Printing.PrintingCanceledException.#ctor\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException()\n  nameWithType: PrintingCanceledException.PrintingCanceledException()\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException()\n- uid: System.Printing.PrintingCanceledException.#ctor(System.String)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(String)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(String)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(Int32,String)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String)\n- uid: System.Int32\n  parent: System\n  isExternal: true\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(SerializationInfo,StreamingContext)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(SerializationInfo,StreamingContext)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Printing.PrintingCanceledException.#ctor(System.String,System.Exception)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(String,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(String,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.Exception)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(Int32,String,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,Exception)\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(Int32,String,String,String,Int32)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32)\n- uid: System.Printing.PrintingCanceledException.#ctor(System.Int32,System.String,System.String,System.String,System.Int32,System.Exception)\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n  nameWithType: PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n  fullName: System.Printing.PrintingCanceledException.PrintingCanceledException(Int32,String,String,String,Int32,Exception)\n- uid: System.Printing.PrintingCanceledException.#ctor*\n  parent: System.Printing.PrintingCanceledException\n  isExternal: false\n  name: PrintingCanceledException\n  nameWithType: PrintingCanceledException.PrintingCanceledException\n"}