{"nodes":[{"pos":[696,883],"content":"The exception that is thrown when an operation is attempted on a transaction that has already been rolled back, or an attempt is made to commit the transaction and the transaction aborts.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when an operation is attempted on a transaction that has already been rolled back, or an attempt is made to commit the transaction and the transaction aborts.","pos":[0,187]}]},{"pos":[896,1299],"content":"This exception is thrown when an action is attempted on a transaction that has already been rolled back, for example, when you attempt to call the <xref:System.Transactions.CommittableTransaction.Commit%2A> method on a transaction that has already timed out. This exception is also thrown when an attempt is made to commit the transaction and the transaction aborts.       This is a recoverable error.","needQuote":false,"needEscape":true,"nodes":[{"content":"This exception is thrown when an action is attempted on a transaction that has already been rolled back, for example, when you attempt to call the <xref:System.Transactions.CommittableTransaction.Commit%2A> method on a transaction that has already timed out. This exception is also thrown when an attempt is made to commit the transaction and the transaction aborts.       This is a recoverable error.","pos":[0,401],"nodes":[{"content":"This exception is thrown when an action is attempted on a transaction that has already been rolled back, for example, when you attempt to call the &lt;xref:System.Transactions.CommittableTransaction.Commit%2A&gt; method on a transaction that has already timed out.","pos":[0,258],"source":"This exception is thrown when an action is attempted on a transaction that has already been rolled back, for example, when you attempt to call the <xref:System.Transactions.CommittableTransaction.Commit%2A> method on a transaction that has already timed out."},{"content":"This exception is also thrown when an attempt is made to commit the transaction and the transaction aborts.","pos":[259,366]},{"content":"This is a recoverable error.","pos":[373,401]}]}]},{"pos":[2038,2147],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Transactions.TransactionAbortedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class."},{"pos":[2841,2977],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Transactions.TransactionAbortedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified message."},{"pos":[3133,3221],"content":"A <xref:System.String> that contains a message that explains why the exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that contains a message that explains why the exception occurred.","pos":[0,88],"source":"A <xref:System.String> that contains a message that explains why the exception occurred."}]},{"pos":[4076,4252],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Transactions.TransactionAbortedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified serialization and streaming context information.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified serialization and streaming context information."},{"pos":[4533,4648],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object that describes a failed serialization.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that describes a failed serialization."},{"pos":[4744,4867],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object that describes a failed serialization context.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that describes a failed serialization context."},{"pos":[5544,5700],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Transactions.TransactionAbortedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message and inner exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified message and inner exception."},{"pos":[5882,5970],"content":"A <xref:System.String> that contains a message that explains why the exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that contains a message that explains why the exception occurred.","pos":[0,88],"source":"A <xref:System.String> that contains a message that explains why the exception occurred."}]},{"pos":[6044,6186],"content":"Gets the exception instance that causes the current exception. For more information, see the <xref:System.Exception.InnerException*> property.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the exception instance that causes the current exception. For more information, see the <xref:System.Exception.InnerException*> property.","pos":[0,142],"nodes":[{"content":"Gets the exception instance that causes the current exception.","pos":[0,62]},{"content":"For more information, see the &lt;xref:System.Exception.InnerException*&gt; property.","pos":[63,142],"source":" For more information, see the <xref:System.Exception.InnerException*> property."}]}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Transactions.TransactionAbortedException\n  id: TransactionAbortedException\n  children:\n  - System.Transactions.TransactionAbortedException.#ctor\n  - System.Transactions.TransactionAbortedException.#ctor(System.String)\n  - System.Transactions.TransactionAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Transactions.TransactionAbortedException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: TransactionAbortedException\n  nameWithType: TransactionAbortedException\n  fullName: System.Transactions.TransactionAbortedException\n  type: Class\n  summary: The exception that is thrown when an operation is attempted on a transaction that has already been rolled back, or an attempt is made to commit the transaction and the transaction aborts.\n  remarks: \"This exception is thrown when an action is attempted on a transaction that has already been rolled back, for example, when you attempt to call the <xref:System.Transactions.CommittableTransaction.Commit%2A> method on a transaction that has already timed out. This exception is also thrown when an attempt is made to commit the transaction and the transaction aborts.  \\n  \\n This is a recoverable error.\"\n  syntax:\n    content: 'public class TransactionAbortedException : System.Transactions.TransactionException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  - System.Transactions.TransactionException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Transactions.TransactionAbortedException.#ctor\n  id: '#ctor'\n  parent: System.Transactions.TransactionAbortedException\n  langs:\n  - csharp\n  name: TransactionAbortedException()\n  nameWithType: TransactionAbortedException.TransactionAbortedException()\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException()\n  type: Constructor\n  assemblies:\n  - System.Transactions\n  namespace: System.Transactions\n  summary: Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class.\n  syntax:\n    content: public TransactionAbortedException ();\n    parameters: []\n  overload: System.Transactions.TransactionAbortedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Transactions.TransactionAbortedException\n  langs:\n  - csharp\n  name: TransactionAbortedException(String)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(String)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(String)\n  type: Constructor\n  assemblies:\n  - System.Transactions\n  namespace: System.Transactions\n  summary: Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified message.\n  syntax:\n    content: public TransactionAbortedException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that contains a message that explains why the exception occurred.\n  overload: System.Transactions.TransactionAbortedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Transactions.TransactionAbortedException\n  langs:\n  - csharp\n  name: TransactionAbortedException(SerializationInfo,StreamingContext)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(SerializationInfo,StreamingContext)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Transactions\n  namespace: System.Transactions\n  summary: Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified serialization and streaming context information.\n  syntax:\n    content: protected TransactionAbortedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that describes a failed serialization.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that describes a failed serialization context.\n  overload: System.Transactions.TransactionAbortedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Transactions.TransactionAbortedException\n  langs:\n  - csharp\n  name: TransactionAbortedException(String,Exception)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(String,Exception)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Transactions\n  namespace: System.Transactions\n  summary: Initializes a new instance of the <xref href=\"System.Transactions.TransactionAbortedException\"></xref> class with the specified message and inner exception.\n  syntax:\n    content: public TransactionAbortedException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that contains a message that explains why the exception occurred.\n    - id: innerException\n      type: System.Exception\n      description: Gets the exception instance that causes the current exception. For more information, see the <xref:System.Exception.InnerException*> property.\n  overload: System.Transactions.TransactionAbortedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Transactions.TransactionException\n  isExternal: false\n  name: System.Transactions.TransactionException\n- uid: System.Transactions.TransactionAbortedException.#ctor\n  parent: System.Transactions.TransactionAbortedException\n  isExternal: false\n  name: TransactionAbortedException()\n  nameWithType: TransactionAbortedException.TransactionAbortedException()\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException()\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.String)\n  parent: System.Transactions.TransactionAbortedException\n  isExternal: false\n  name: TransactionAbortedException(String)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(String)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Transactions.TransactionAbortedException\n  isExternal: false\n  name: TransactionAbortedException(SerializationInfo,StreamingContext)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(SerializationInfo,StreamingContext)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Transactions.TransactionAbortedException.#ctor(System.String,System.Exception)\n  parent: System.Transactions.TransactionAbortedException\n  isExternal: false\n  name: TransactionAbortedException(String,Exception)\n  nameWithType: TransactionAbortedException.TransactionAbortedException(String,Exception)\n  fullName: System.Transactions.TransactionAbortedException.TransactionAbortedException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Transactions.TransactionAbortedException.#ctor*\n  parent: System.Transactions.TransactionAbortedException\n  isExternal: false\n  name: TransactionAbortedException\n  nameWithType: TransactionAbortedException.TransactionAbortedException\n"}