{"nodes":[{"pos":[1207,1562],"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","pos":[0,355],"nodes":[{"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance.","pos":[0,168]},{"content":"Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","pos":[169,355]}]}]},{"pos":[1575,2498],"content":"> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]       The WorkflowOwnershipException is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SQLWorkflowPersistenceService> class throws the WorkflowOwnershipException when this situation occurs.       If you implement a persistence service that throws the WorkflowOwnershipException you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"<ph id=\"ph1\">&gt; [!NOTE]</ph><ph id=\"ph2\"> &gt;  </ph><ph id=\"ph3\">[!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]</ph>       The WorkflowOwnershipException is used by persistence services which support the capability for multiple applications to access the same database.","pos":[0,234],"source":"> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]       The WorkflowOwnershipException is used by persistence services which support the capability for multiple applications to access the same database."},{"content":"In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine.","pos":[235,396]},{"content":"For example, the &lt;xref:System.Workflow.Runtime.Hosting.SQLWorkflowPersistenceService&gt; class throws the WorkflowOwnershipException when this situation occurs.","pos":[397,554],"source":" For example, the <xref:System.Workflow.Runtime.Hosting.SQLWorkflowPersistenceService> class throws the WorkflowOwnershipException when this situation occurs."},{"content":"If you implement a persistence service that throws the WorkflowOwnershipException you should provide the &lt;xref:System.Guid&gt; of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt; property before you throw the exception.","pos":[561,918],"source":"       If you implement a persistence service that throws the WorkflowOwnershipException you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception."}]},{"pos":[3285,3397],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class."},{"pos":[3410,4086],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|A system-supplied localized description.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.","pos":[0,201],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[208,339],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)|   |&lt;xref:System.Exception.Message%2A&gt;|A system-supplied localized description.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|An empty &lt;xref:System.Guid&gt;.|","pos":[345,668],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|A system-supplied localized description.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|"}]},{"pos":[4786,4956],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by using a specified workflow instance &lt;xref:System.Guid&gt;.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid>."},{"pos":[4969,5869],"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|A system-supplied localized description.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance.","pos":[0,155],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The &lt;xref:System.Exception.Message%2A&gt; property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.","pos":[156,343],"source":" The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[350,481],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)|   |&lt;xref:System.Exception.Message%2A&gt;|A system-supplied localized description.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|The &lt;xref:System.Guid&gt; of the workflow instance, specified by <ph id=\"ph2\">`instanceId`</ph>, for which this exception occurred.|","pos":[487,892],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|A system-supplied localized description.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|"}]},{"pos":[6027,6109],"content":"The <xref:System.Guid> of the workflow instance for which this exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Guid&gt; of the workflow instance for which this exception occurred.","pos":[0,82],"source":"The <xref:System.Guid> of the workflow instance for which this exception occurred."}]},{"pos":[6738,6885],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by using a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message."},{"pos":[6898,7716],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]},{"content":"If you use this constructor you should explicitly set &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt; before you throw the exception.","pos":[200,357],"source":" If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[364,495],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|An empty &lt;xref:System.Guid&gt;.|","pos":[501,810],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|"}]},{"pos":[7872,7909],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[8577,8777],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by using a specified workflow instance &lt;xref:System.Guid&gt; and a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid> and a specified error message."},{"pos":[8790,9687],"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance.","pos":[0,155],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[156,234],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[235,355]},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[362,493],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|The &lt;xref:System.Guid&gt; of the workflow instance, specified by <ph id=\"ph2\">`instanceId`</ph>, for which this exception occurred.|","pos":[499,889],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|"}]},{"pos":[9861,9943],"content":"The <xref:System.Guid> of the workflow instance for which this exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Guid&gt; of the workflow instance for which this exception occurred.","pos":[0,82],"source":"The <xref:System.Guid> of the workflow instance for which this exception occurred."}]},{"pos":[10007,10044],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[10915,11003],"content":"Initializes a new instance of the WorkflowOwnershipException class with serialized data.","needQuote":true,"needEscape":true,"nodes":[{"content":"Initializes a new instance of the WorkflowOwnershipException class with serialized data.","pos":[0,88]}]},{"pos":[11016,11188],"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.       For more information see XML and SOAP Serialization.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.       For more information see XML and SOAP Serialization.","pos":[0,170],"nodes":[{"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.","pos":[0,111]},{"content":"For more information see XML and SOAP Serialization.","pos":[118,170]}]}]},{"pos":[11469,11610],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[11706,11830],"content":"A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.","pos":[0,124],"source":"A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."}]},{"pos":[12523,12745],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by using a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[12758,14000],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the <ph id=\"ph1\">`innerException`</ph> parameter does not supply the inner exception value to the constructor.","pos":[183,438],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[439,517],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[518,638]},{"content":"If you use this constructor you should explicitly set &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt; before you throw the exception.","pos":[639,796],"source":" If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[803,934],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|An empty &lt;xref:System.Guid&gt;.|","pos":[940,1234],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|"}]},{"pos":[14182,14219],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[14293,14577],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not a null reference (<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","pos":[58,284],"source":" If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception."}]},{"pos":[15309,15582],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by using a specified workflow instance &lt;xref:System.Guid&gt;, a specified error message, and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid>, a specified error message, and a reference to the inner exception that is the cause of this exception."},{"pos":[15595,16925],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor.       `instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the <ph id=\"ph1\">`innerException`</ph> parameter does not supply the inner exception value to the constructor.","pos":[183,438],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor."},{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance.","pos":[445,600],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[601,679],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[680,800]},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;.","pos":[807,938],"source":"       The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;|The &lt;xref:System.Guid&gt; of the workflow instance, specified by <ph id=\"ph1\">`instanceId`</ph>, for which this exception occurred.|","pos":[944,1320],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|   |<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|"}]},{"pos":[17125,17207],"content":"The <xref:System.Guid> of the workflow instance for which this exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Guid&gt; of the workflow instance for which this exception occurred.","pos":[0,82],"source":"The <xref:System.Guid> of the workflow instance for which this exception occurred."}]},{"pos":[17271,17308],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[17382,17666],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not a null reference (<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","pos":[58,284],"source":" If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception."}]},{"pos":[18507,18713],"content":"Sets the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object with the &lt;xref:System.Guid&gt; of the workflow instance associated with this exception, and additional exception information.","needQuote":true,"needEscape":true,"source":"Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the <xref:System.Guid> of the workflow instance associated with this exception, and additional exception information."},{"pos":[18726,19077],"content":"GetObjectData sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.       For more information see XML and SOAP Serialization.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"GetObjectData sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.       For more information see XML and SOAP Serialization.","pos":[0,349],"nodes":[{"content":"GetObjectData sets a &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; with all the exception object data targeted for serialization.","pos":[0,137],"source":"GetObjectData sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization."},{"content":"During deserialization the exception object is reconstituted from the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; transmitted over the stream.","pos":[138,290],"source":" During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream."},{"content":"For more information see XML and SOAP Serialization.","pos":[297,349]}]}]},{"pos":[19356,19497],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[19593,19717],"content":"A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.","pos":[0,124],"source":"A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."}]},{"pos":[19912,20034],"content":"<ph id=\"ph1\">&lt;code&gt;info&lt;/code&gt;</ph> is a null reference (<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> in Visual Basic)","needQuote":true,"needEscape":true,"source":"<code>info</code> is a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic)"},{"pos":[20479,20568],"content":"Gets the <xref:System.Guid> of the workflow instance for which this exception was thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the &lt;xref:System.Guid&gt; of the workflow instance for which this exception was thrown.","pos":[0,89],"source":"Gets the <xref:System.Guid> of the workflow instance for which this exception was thrown."}]},{"pos":[20684,20843],"content":"InstanceId is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance.","needQuote":true,"needEscape":true,"nodes":[{"content":"InstanceId is equivalent to the <ph id=\"ph1\">&amp;lt;</ph>xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName<ph id=\"ph2\">&amp;gt;</ph> property of the workflow instance.","pos":[0,159],"source":"InstanceId is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Workflow.Runtime.WorkflowOwnershipException\n  id: WorkflowOwnershipException\n  children:\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  - System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  langs:\n  - csharp\n  name: WorkflowOwnershipException\n  nameWithType: WorkflowOwnershipException\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException\n  type: Class\n  summary: The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.\n  remarks: \"> [!NOTE]\\n>  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]  \\n  \\n The WorkflowOwnershipException is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SQLWorkflowPersistenceService> class throws the WorkflowOwnershipException when this situation occurs.  \\n  \\n If you implement a persistence service that throws the WorkflowOwnershipException you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception.\"\n  syntax:\n    content: >-\n      [System.Obsolete(\"The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*\")]\n\n      public class WorkflowOwnershipException : Exception\n  inheritance:\n  - System.Exception\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  id: '#ctor'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException()\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException()\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException()\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException ();\n    parameters: []\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  id: '#ctor(System.Guid)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid>.\n  remarks: \"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref:System.Guid> of the workflow instance for which this exception occurred.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(String)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  id: '#ctor(System.Guid,System.String)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid,String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid,String)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid,String)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid> and a specified error message.\n  remarks: \"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId, string message);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref:System.Guid> of the workflow instance for which this exception occurred.\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(SerializationInfo,StreamingContext)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo,StreamingContext)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the WorkflowOwnershipException class with serialized data.\n  remarks: \"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.  \\n  \\n For more information see XML and SOAP Serialization.\"\n  syntax:\n    content: protected WorkflowOwnershipException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(String,Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String,Exception)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  id: '#ctor(System.Guid,System.String,System.Exception)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid,String,Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid,String,Exception)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid,String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref:System.Guid>, a specified error message, and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor.  \\n  \\n `instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId, string message, Exception innerException);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref:System.Guid> of the workflow instance for which this exception occurred.\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo,StreamingContext)\n  nameWithType: WorkflowOwnershipException.GetObjectData(SerializationInfo,StreamingContext)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(SerializationInfo,StreamingContext)\n  type: Method\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the <xref:System.Guid> of the workflow instance associated with this exception, and additional exception information.\n  remarks: \"GetObjectData sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.  \\n  \\n For more information see XML and SOAP Serialization.\"\n  syntax:\n    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: <code>info</code> is a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic)\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  id: InstanceId\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  type: Property\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Gets the <xref:System.Guid> of the workflow instance for which this exception was thrown.\n  syntax:\n    content: public Guid InstanceId { get; set; }\n    return:\n      type: System.Guid\n      description: InstanceId is equivalent to the &lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt; property of the workflow instance.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Exception\n  isExternal: false\n  name: System.Exception\n- uid: System.ArgumentNullException\n  isExternal: true\n  name: System.ArgumentNullException\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException()\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException()\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException()\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n- uid: System.Guid\n  parent: System\n  isExternal: true\n  name: Guid\n  nameWithType: Guid\n  fullName: System.Guid\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid,String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid,String)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid,String)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(SerializationInfo,StreamingContext)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo,StreamingContext)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(String,Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String,Exception)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(String,Exception)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid,String,Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid,String,Exception)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.WorkflowOwnershipException(Guid,String,Exception)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: GetObjectData(SerializationInfo,StreamingContext)\n  nameWithType: WorkflowOwnershipException.GetObjectData(SerializationInfo,StreamingContext)\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(SerializationInfo,StreamingContext)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: WorkflowOwnershipException.GetObjectData\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n"}