{"nodes":[{"pos":[630,834],"content":"The exception that is thrown when a XAML writer (such as the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlObjectWriter\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class) encounters an error while attempting to produce object graphs from a XAML node stream.","needQuote":true,"needEscape":true,"source":"The exception that is thrown when a XAML writer (such as the <xref href=\"System.Xaml.XamlObjectWriter\"></xref> class) encounters an error while attempting to produce object graphs from a XAML node stream."},{"pos":[846,1429],"content":"For cases where line information is available (such as when the XAML node stream was read by a <xref:System.Xaml.XamlXmlReader>), and for certain exception cases, a XamlObjectWriterException can report line information from the source of the XAML node stream. This information is appended to the <xref:System.Xaml.XamlException.Message%2A> and is also contained in <xref:System.Xaml.XamlException.LineNumber%2A> and <xref:System.Xaml.XamlException.LinePosition%2A>. Each of these members is implemented by the <xref:System.Xaml.XamlException> base class of XamlObjectWriterException.","needQuote":true,"needEscape":true,"nodes":[{"content":"For cases where line information is available (such as when the XAML node stream was read by a <xref:System.Xaml.XamlXmlReader>), and for certain exception cases, a XamlObjectWriterException can report line information from the source of the XAML node stream. This information is appended to the <xref:System.Xaml.XamlException.Message%2A> and is also contained in <xref:System.Xaml.XamlException.LineNumber%2A> and <xref:System.Xaml.XamlException.LinePosition%2A>. Each of these members is implemented by the <xref:System.Xaml.XamlException> base class of XamlObjectWriterException.","pos":[0,583],"nodes":[{"content":"For cases where line information is available (such as when the XAML node stream was read by a &lt;xref:System.Xaml.XamlXmlReader&gt;), and for certain exception cases, a XamlObjectWriterException can report line information from the source of the XAML node stream.","pos":[0,259],"source":"For cases where line information is available (such as when the XAML node stream was read by a <xref:System.Xaml.XamlXmlReader>), and for certain exception cases, a XamlObjectWriterException can report line information from the source of the XAML node stream."},{"content":"This information is appended to the &lt;xref:System.Xaml.XamlException.Message%2A&gt; and is also contained in &lt;xref:System.Xaml.XamlException.LineNumber%2A&gt; and &lt;xref:System.Xaml.XamlException.LinePosition%2A&gt;.","pos":[260,465],"source":" This information is appended to the <xref:System.Xaml.XamlException.Message%2A> and is also contained in <xref:System.Xaml.XamlException.LineNumber%2A> and <xref:System.Xaml.XamlException.LinePosition%2A>."},{"content":"Each of these members is implemented by the &lt;xref:System.Xaml.XamlException&gt; base class of XamlObjectWriterException.","pos":[466,583],"source":" Each of these members is implemented by the <xref:System.Xaml.XamlException> base class of XamlObjectWriterException."}]}]},{"pos":[2311,2466],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlObjectWriterException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a system-supplied message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a system-supplied message that describes the error."},{"pos":[3094,3243],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlObjectWriterException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a specified message that describes the error."},{"pos":[3397,3559],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[4350,4470],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlObjectWriterException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with serialized data."},{"pos":[4749,4798],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[4894,4953],"content":"The contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]},{"pos":[5566,5771],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlObjectWriterException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[5783,6210],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","needQuote":true,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[6390,6552],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[6626,6926],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,300],"source":" If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Xaml.XamlObjectWriterException\n  id: XamlObjectWriterException\n  children:\n  - System.Xaml.XamlObjectWriterException.#ctor\n  - System.Xaml.XamlObjectWriterException.#ctor(System.String)\n  - System.Xaml.XamlObjectWriterException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlObjectWriterException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: XamlObjectWriterException\n  nameWithType: XamlObjectWriterException\n  fullName: System.Xaml.XamlObjectWriterException\n  type: Class\n  summary: The exception that is thrown when a XAML writer (such as the <xref href=\"System.Xaml.XamlObjectWriter\"></xref> class) encounters an error while attempting to produce object graphs from a XAML node stream.\n  remarks: For cases where line information is available (such as when the XAML node stream was read by a <xref:System.Xaml.XamlXmlReader>), and for certain exception cases, a XamlObjectWriterException can report line information from the source of the XAML node stream. This information is appended to the <xref:System.Xaml.XamlException.Message%2A> and is also contained in <xref:System.Xaml.XamlException.LineNumber%2A> and <xref:System.Xaml.XamlException.LinePosition%2A>. Each of these members is implemented by the <xref:System.Xaml.XamlException> base class of XamlObjectWriterException.\n  syntax:\n    content: 'public class XamlObjectWriterException : System.Xaml.XamlException'\n  inheritance:\n  - System.Exception\n  - System.Xaml.XamlException\n  implements: []\n  inheritedMembers:\n  - System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlException.LineNumber\n  - System.Xaml.XamlException.LinePosition\n  - System.Xaml.XamlException.Message\n  platform:\n  - net462\n- uid: System.Xaml.XamlObjectWriterException.#ctor\n  id: '#ctor'\n  parent: System.Xaml.XamlObjectWriterException\n  langs:\n  - csharp\n  name: XamlObjectWriterException()\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException()\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException()\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a system-supplied message that describes the error.\n  syntax:\n    content: public XamlObjectWriterException ();\n    parameters: []\n  overload: System.Xaml.XamlObjectWriterException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Xaml.XamlObjectWriterException\n  langs:\n  - csharp\n  name: XamlObjectWriterException(String)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(String)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(String)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a specified message that describes the error.\n  syntax:\n    content: public XamlObjectWriterException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: System.Xaml.XamlObjectWriterException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Xaml.XamlObjectWriterException\n  langs:\n  - csharp\n  name: XamlObjectWriterException(SerializationInfo,StreamingContext)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(SerializationInfo,StreamingContext)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with serialized data.\n  syntax:\n    content: protected XamlObjectWriterException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Xaml.XamlObjectWriterException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Xaml.XamlObjectWriterException\n  langs:\n  - csharp\n  name: XamlObjectWriterException(String,Exception)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(String,Exception)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlObjectWriterException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.\n  syntax:\n    content: public XamlObjectWriterException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.Xaml.XamlObjectWriterException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Xaml.XamlException\n  isExternal: false\n  name: System.Xaml.XamlException\n- uid: System.Xaml.XamlObjectWriterException.#ctor\n  parent: System.Xaml.XamlObjectWriterException\n  isExternal: false\n  name: XamlObjectWriterException()\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException()\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException()\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.String)\n  parent: System.Xaml.XamlObjectWriterException\n  isExternal: false\n  name: XamlObjectWriterException(String)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(String)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Xaml.XamlObjectWriterException\n  isExternal: false\n  name: XamlObjectWriterException(SerializationInfo,StreamingContext)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(SerializationInfo,StreamingContext)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Xaml.XamlObjectWriterException.#ctor(System.String,System.Exception)\n  parent: System.Xaml.XamlObjectWriterException\n  isExternal: false\n  name: XamlObjectWriterException(String,Exception)\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException(String,Exception)\n  fullName: System.Xaml.XamlObjectWriterException.XamlObjectWriterException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Xaml.XamlObjectWriterException.#ctor*\n  parent: System.Xaml.XamlObjectWriterException\n  isExternal: false\n  name: XamlObjectWriterException\n  nameWithType: XamlObjectWriterException.XamlObjectWriterException\n"}