{"nodes":[{"pos":[612,692],"content":"The exception that is thrown when a workflow or activity is in an invalid state.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when a workflow or activity is in an invalid state.","pos":[0,80]}]},{"pos":[1286,1406],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Activities.ValidationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using default values.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class using default values."},{"pos":[2016,2146],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Activities.ValidationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with a specified error message."},{"pos":[2294,2355],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[3134,3254],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Activities.ValidationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with serialized data."},{"pos":[3527,3670],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[3766,3892],"content":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.","pos":[0,126],"source":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."}]},{"pos":[4493,4698],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Activities.ValidationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[4872,4933],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[5007,5205],"content":"The exception that is the cause of the current exception, or a null reference (<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> in Visual Basic) if no inner exception is specified.","needQuote":true,"needEscape":true,"source":"The exception that is the cause of the current exception, or a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic) if no inner exception is specified."}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Activities.ValidationException\n  id: ValidationException\n  children:\n  - System.Activities.ValidationException.#ctor\n  - System.Activities.ValidationException.#ctor(System.String)\n  - System.Activities.ValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Activities.ValidationException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ValidationException\n  nameWithType: ValidationException\n  fullName: System.Activities.ValidationException\n  type: Class\n  summary: The exception that is thrown when a workflow or activity is in an invalid state.\n  syntax:\n    content: 'public class ValidationException : SystemException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Activities.ValidationException.#ctor\n  id: '#ctor'\n  parent: System.Activities.ValidationException\n  langs:\n  - csharp\n  name: ValidationException()\n  nameWithType: ValidationException.ValidationException()\n  fullName: System.Activities.ValidationException.ValidationException()\n  type: Constructor\n  assemblies:\n  - System.Activities\n  namespace: System.Activities\n  summary: Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class using default values.\n  syntax:\n    content: public ValidationException ();\n    parameters: []\n  overload: System.Activities.ValidationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Activities.ValidationException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Activities.ValidationException\n  langs:\n  - csharp\n  name: ValidationException(String)\n  nameWithType: ValidationException.ValidationException(String)\n  fullName: System.Activities.ValidationException.ValidationException(String)\n  type: Constructor\n  assemblies:\n  - System.Activities\n  namespace: System.Activities\n  summary: Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with a specified error message.\n  syntax:\n    content: public ValidationException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.Activities.ValidationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Activities.ValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Activities.ValidationException\n  langs:\n  - csharp\n  name: ValidationException(SerializationInfo,StreamingContext)\n  nameWithType: ValidationException.ValidationException(SerializationInfo,StreamingContext)\n  fullName: System.Activities.ValidationException.ValidationException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Activities\n  namespace: System.Activities\n  summary: Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with serialized data.\n  syntax:\n    content: protected ValidationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.\n  overload: System.Activities.ValidationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Activities.ValidationException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Activities.ValidationException\n  langs:\n  - csharp\n  name: ValidationException(String,Exception)\n  nameWithType: ValidationException.ValidationException(String,Exception)\n  fullName: System.Activities.ValidationException.ValidationException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Activities\n  namespace: System.Activities\n  summary: Initializes a new instance of the <xref href=\"System.Activities.ValidationException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  syntax:\n    content: public ValidationException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception, or a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic) if no inner exception is specified.\n  overload: System.Activities.ValidationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n- uid: System.Activities.ValidationException.#ctor\n  parent: System.Activities.ValidationException\n  isExternal: false\n  name: ValidationException()\n  nameWithType: ValidationException.ValidationException()\n  fullName: System.Activities.ValidationException.ValidationException()\n- uid: System.Activities.ValidationException.#ctor(System.String)\n  parent: System.Activities.ValidationException\n  isExternal: false\n  name: ValidationException(String)\n  nameWithType: ValidationException.ValidationException(String)\n  fullName: System.Activities.ValidationException.ValidationException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Activities.ValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Activities.ValidationException\n  isExternal: false\n  name: ValidationException(SerializationInfo,StreamingContext)\n  nameWithType: ValidationException.ValidationException(SerializationInfo,StreamingContext)\n  fullName: System.Activities.ValidationException.ValidationException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Activities.ValidationException.#ctor(System.String,System.Exception)\n  parent: System.Activities.ValidationException\n  isExternal: false\n  name: ValidationException(String,Exception)\n  nameWithType: ValidationException.ValidationException(String,Exception)\n  fullName: System.Activities.ValidationException.ValidationException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Activities.ValidationException.#ctor*\n  parent: System.Activities.ValidationException\n  isExternal: false\n  name: ValidationException\n  nameWithType: ValidationException.ValidationException\n"}