{"nodes":[{"pos":[582,680],"content":"The exception that is thrown when an attempt to marshal an object across a context boundary fails.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when an attempt to marshal an object across a context boundary fails.","pos":[0,98]}]},{"pos":[693,1254],"content":"Objects can marshal by value or by reference. Any attempt to pass a type that cannot be marshaled through a context boundary will result in a ContextMarshalException.       ContextMarshalException uses the HRESULT COR_E_CONTEXTMARSHAL which has the value 0x80131504L.       ContextMarshalException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.       For a list of initial property values for an instance of ContextMarshalException, see the <xref:System.ContextMarshalException.%23ctor%2A> constructors.","needQuote":false,"needEscape":true,"nodes":[{"content":"Objects can marshal by value or by reference. Any attempt to pass a type that cannot be marshaled through a context boundary will result in a ContextMarshalException.       ContextMarshalException uses the HRESULT COR_E_CONTEXTMARSHAL which has the value 0x80131504L.       ContextMarshalException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.       For a list of initial property values for an instance of ContextMarshalException, see the <xref:System.ContextMarshalException.%23ctor%2A> constructors.","pos":[0,555],"nodes":[{"content":"Objects can marshal by value or by reference.","pos":[0,45]},{"content":"Any attempt to pass a type that cannot be marshaled through a context boundary will result in a ContextMarshalException.","pos":[46,166]},{"content":"ContextMarshalException uses the HRESULT COR_E_CONTEXTMARSHAL which has the value 0x80131504L.","pos":[173,267]},{"content":"ContextMarshalException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.","pos":[274,396],"source":"       ContextMarshalException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality."},{"content":"For a list of initial property values for an instance of ContextMarshalException, see the &lt;xref:System.ContextMarshalException.%23ctor%2A&gt; constructors.","pos":[403,555],"source":"       For a list of initial property values for an instance of ContextMarshalException, see the <xref:System.ContextMarshalException.%23ctor%2A> constructors."}]}]},{"pos":[1892,2008],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ContextMarshalException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with default properties.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with default properties."},{"pos":[2021,2308],"content":"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The empty string (\"\").|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.","pos":[0,111],"source":"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string (\"\").|","pos":[117,280],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The empty string (\"\").|"}]},{"pos":[2891,3014],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ContextMarshalException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with a specified error message."},{"pos":[3027,3315],"content":"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.","pos":[0,111],"source":"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[117,283],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[3468,3529],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[4276,4389],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ContextMarshalException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with serialized data."},{"pos":[4666,4809],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[4905,5031],"content":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.","pos":[0,126],"source":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."}]},{"pos":[5600,5798],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ContextMarshalException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[5811,6558],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ContextMarshalException&gt;.","pos":[434,545],"source":"       The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[551,740],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[6728,6789],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[6854,7145],"content":"The exception that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`inner`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,291],"source":" If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.ContextMarshalException\n  id: ContextMarshalException\n  children:\n  - System.ContextMarshalException.#ctor\n  - System.ContextMarshalException.#ctor(System.String)\n  - System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.ContextMarshalException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ContextMarshalException\n  nameWithType: ContextMarshalException\n  fullName: System.ContextMarshalException\n  type: Class\n  summary: The exception that is thrown when an attempt to marshal an object across a context boundary fails.\n  remarks: \"Objects can marshal by value or by reference. Any attempt to pass a type that cannot be marshaled through a context boundary will result in a ContextMarshalException.  \\n  \\n ContextMarshalException uses the HRESULT COR_E_CONTEXTMARSHAL which has the value 0x80131504L.  \\n  \\n ContextMarshalException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \\n  \\n For a list of initial property values for an instance of ContextMarshalException, see the <xref:System.ContextMarshalException.%23ctor%2A> constructors.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class ContextMarshalException : SystemException\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.ContextMarshalException.#ctor\n  id: '#ctor'\n  parent: System.ContextMarshalException\n  langs:\n  - csharp\n  name: ContextMarshalException()\n  nameWithType: ContextMarshalException.ContextMarshalException()\n  fullName: System.ContextMarshalException.ContextMarshalException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with default properties.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The empty string (\\\"\\\").|\"\n  syntax:\n    content: public ContextMarshalException ();\n    parameters: []\n  overload: System.ContextMarshalException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ContextMarshalException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.ContextMarshalException\n  langs:\n  - csharp\n  name: ContextMarshalException(String)\n  nameWithType: ContextMarshalException.ContextMarshalException(String)\n  fullName: System.ContextMarshalException.ContextMarshalException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ContextMarshalException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.ContextMarshalException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.ContextMarshalException\n  langs:\n  - csharp\n  name: ContextMarshalException(SerializationInfo,StreamingContext)\n  nameWithType: ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)\n  fullName: System.ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with serialized data.\n  syntax:\n    content: protected ContextMarshalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.\n  overload: System.ContextMarshalException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ContextMarshalException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.ContextMarshalException\n  langs:\n  - csharp\n  name: ContextMarshalException(String,Exception)\n  nameWithType: ContextMarshalException.ContextMarshalException(String,Exception)\n  fullName: System.ContextMarshalException.ContextMarshalException(String,Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ContextMarshalException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ContextMarshalException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ContextMarshalException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.ContextMarshalException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n- uid: System.ContextMarshalException.#ctor\n  parent: System.ContextMarshalException\n  isExternal: false\n  name: ContextMarshalException()\n  nameWithType: ContextMarshalException.ContextMarshalException()\n  fullName: System.ContextMarshalException.ContextMarshalException()\n- uid: System.ContextMarshalException.#ctor(System.String)\n  parent: System.ContextMarshalException\n  isExternal: false\n  name: ContextMarshalException(String)\n  nameWithType: ContextMarshalException.ContextMarshalException(String)\n  fullName: System.ContextMarshalException.ContextMarshalException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.ContextMarshalException\n  isExternal: false\n  name: ContextMarshalException(SerializationInfo,StreamingContext)\n  nameWithType: ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)\n  fullName: System.ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.ContextMarshalException.#ctor(System.String,System.Exception)\n  parent: System.ContextMarshalException\n  isExternal: false\n  name: ContextMarshalException(String,Exception)\n  nameWithType: ContextMarshalException.ContextMarshalException(String,Exception)\n  fullName: System.ContextMarshalException.ContextMarshalException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ContextMarshalException.#ctor*\n  parent: System.ContextMarshalException\n  isExternal: false\n  name: ContextMarshalException\n  nameWithType: ContextMarshalException.ContextMarshalException\n"}