{"nodes":[{"pos":[940,1032],"content":"Exception that indicates an error occurred loading the property value from the data service.","needQuote":true,"needEscape":true,"nodes":[{"content":"Exception that indicates an error occurred loading the property value from the data service.","pos":[0,92]}]},{"pos":[1044,1172],"content":"The caller should inspect <xref:System.Data.Services.Client.DataServiceQueryException.Response%2A> to get the exception results.","needQuote":true,"needEscape":true,"nodes":[{"content":"The caller should inspect &lt;xref:System.Data.Services.Client.DataServiceQueryException.Response%2A&gt; to get the exception results.","pos":[0,128],"source":"The caller should inspect <xref:System.Data.Services.Client.DataServiceQueryException.Response%2A> to get the exception results."}]},{"pos":[1934,2105],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.DataServiceQueryException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a system-supplied message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a system-supplied message that describes the error."},{"pos":[2118,2640],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error.","pos":[0,151],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error."},{"content":"This message takes into account the current system culture.","pos":[152,211]},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.InsufficientMemoryException&gt;.","pos":[218,333],"source":"       The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[339,515],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]},{"pos":[3365,3530],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.DataServiceQueryException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a specified message that describes the error."},{"pos":[3543,3877],"content":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Data.Services.Client.DataServiceQueryException&gt;.","pos":[0,134],"source":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string specified in <ph id=\"ph2\">`message`</ph>.|","pos":[140,329],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|"}]},{"pos":[4032,4194],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[5348,5360],"content":"To be added.","needQuote":true,"needEscape":true,"nodes":[{"content":"To be added.","pos":[0,12]}]},{"pos":[5456,5468],"content":"To be added.","needQuote":true,"needEscape":true,"nodes":[{"content":"To be added.","pos":[0,12]}]},{"pos":[6177,6398],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.DataServiceQueryException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[6411,7181],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","needQuote":false,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Data.Services.Client.DataServiceQueryException&gt;.","pos":[434,568],"source":"       The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string specified in <ph id=\"ph2\">`message`</ph>.|","pos":[574,763],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|"}]},{"pos":[7362,7524],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[7598,7898],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,300],"source":" If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]},{"pos":[8778,8893],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.DataServiceQueryException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class."},{"pos":[9134,9183],"content":"The string value that contains the error message.","needQuote":true,"needEscape":true,"nodes":[{"content":"The string value that contains the error message.","pos":[0,49]}]},{"pos":[9257,9284],"content":"The inner exception object.","needQuote":true,"needEscape":true,"nodes":[{"content":"The inner exception object.","pos":[0,27]}]},{"pos":[9386,9469],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.QueryOperationResponse\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> object."},{"pos":[10010,10128],"content":"Gets the <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.QueryOperationResponse\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that indicates the exception results.","needQuote":true,"needEscape":true,"source":"Gets the <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> that indicates the exception results."},{"pos":[10322,10440],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Data.Services.Client.QueryOperationResponse\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object that indicates the exception results.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> object that indicates the exception results."}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Data.Services.Client.DataServiceQueryException\n  id: DataServiceQueryException\n  children:\n  - System.Data.Services.Client.DataServiceQueryException.#ctor\n  - System.Data.Services.Client.DataServiceQueryException.#ctor(System.String)\n  - System.Data.Services.Client.DataServiceQueryException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception)\n  - System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception,System.Data.Services.Client.QueryOperationResponse)\n  - System.Data.Services.Client.DataServiceQueryException.Response\n  langs:\n  - csharp\n  name: DataServiceQueryException\n  nameWithType: DataServiceQueryException\n  fullName: System.Data.Services.Client.DataServiceQueryException\n  type: Class\n  summary: Exception that indicates an error occurred loading the property value from the data service.\n  remarks: The caller should inspect <xref:System.Data.Services.Client.DataServiceQueryException.Response%2A> to get the exception results.\n  syntax:\n    content: >-\n      [System.Diagnostics.DebuggerDisplay(\"{Message}\")]\n\n      public sealed class DataServiceQueryException : InvalidOperationException\n  inheritance:\n  - System.InvalidOperationException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor\n  id: '#ctor'\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: DataServiceQueryException()\n  nameWithType: DataServiceQueryException.DataServiceQueryException()\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException()\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a system-supplied message that describes the error.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public DataServiceQueryException ();\n    parameters: []\n  overload: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: DataServiceQueryException(String)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a specified message that describes the error.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public DataServiceQueryException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: DataServiceQueryException(SerializationInfo,StreamingContext)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(SerializationInfo,StreamingContext)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  syntax:\n    content: protected DataServiceQueryException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: To be added.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: To be added.\n  overload: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: DataServiceQueryException(String,Exception)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String,Exception)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceQueryException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public DataServiceQueryException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception,System.Data.Services.Client.QueryOperationResponse)\n  id: '#ctor(System.String,System.Exception,System.Data.Services.Client.QueryOperationResponse)'\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: DataServiceQueryException(String,Exception,QueryOperationResponse)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String,Exception,QueryOperationResponse)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String,Exception,QueryOperationResponse)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceQueryException\"></xref> class.\n  syntax:\n    content: public DataServiceQueryException (string message, Exception innerException, System.Data.Services.Client.QueryOperationResponse response);\n    parameters:\n    - id: message\n      type: System.String\n      description: The string value that contains the error message.\n    - id: innerException\n      type: System.Exception\n      description: The inner exception object.\n    - id: response\n      type: System.Data.Services.Client.QueryOperationResponse\n      description: The <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> object.\n  overload: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Services.Client.DataServiceQueryException.Response\n  id: Response\n  parent: System.Data.Services.Client.DataServiceQueryException\n  langs:\n  - csharp\n  name: Response\n  nameWithType: DataServiceQueryException.Response\n  fullName: System.Data.Services.Client.DataServiceQueryException.Response\n  type: Property\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Gets the <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> that indicates the exception results.\n  syntax:\n    content: public System.Data.Services.Client.QueryOperationResponse Response { get; }\n    return:\n      type: System.Data.Services.Client.QueryOperationResponse\n      description: A <xref href=\"System.Data.Services.Client.QueryOperationResponse\"></xref> object that indicates the exception results.\n  overload: System.Data.Services.Client.DataServiceQueryException.Response*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.InvalidOperationException\n  isExternal: false\n  name: System.InvalidOperationException\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException()\n  nameWithType: DataServiceQueryException.DataServiceQueryException()\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException()\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String)\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException(String)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException(SerializationInfo,StreamingContext)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(SerializationInfo,StreamingContext)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception)\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException(String,Exception)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String,Exception)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor(System.String,System.Exception,System.Data.Services.Client.QueryOperationResponse)\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException(String,Exception,QueryOperationResponse)\n  nameWithType: DataServiceQueryException.DataServiceQueryException(String,Exception,QueryOperationResponse)\n  fullName: System.Data.Services.Client.DataServiceQueryException.DataServiceQueryException(String,Exception,QueryOperationResponse)\n- uid: System.Data.Services.Client.QueryOperationResponse\n  parent: System.Data.Services.Client\n  isExternal: false\n  name: QueryOperationResponse\n  nameWithType: QueryOperationResponse\n  fullName: System.Data.Services.Client.QueryOperationResponse\n- uid: System.Data.Services.Client.DataServiceQueryException.Response\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: Response\n  nameWithType: DataServiceQueryException.Response\n  fullName: System.Data.Services.Client.DataServiceQueryException.Response\n- uid: System.Data.Services.Client.DataServiceQueryException.#ctor*\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: DataServiceQueryException\n  nameWithType: DataServiceQueryException.DataServiceQueryException\n- uid: System.Data.Services.Client.DataServiceQueryException.Response*\n  parent: System.Data.Services.Client.DataServiceQueryException\n  isExternal: false\n  name: Response\n  nameWithType: DataServiceQueryException.Response\n"}