{"nodes":[{"pos":[576,763],"content":"The exception that is thrown when a &lt;xref:System.Net.NetworkInformation.Ping.Send<bpt id=\"p1\">*</bpt>&gt; or &lt;xref:System.Net.NetworkInformation.Ping.SendAsync<ept id=\"p1\">*</ept>&gt; method calls a method that throws an exception.","needQuote":true,"needEscape":true,"source":"The exception that is thrown when a <xref:System.Net.NetworkInformation.Ping.Send*> or <xref:System.Net.NetworkInformation.Ping.SendAsync*> method calls a method that throws an exception."},{"pos":[776,1587],"content":"The <xref:System.Net.NetworkInformation.Ping> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <xref:System.Net.NetworkInformation.Ping> class threw an unhandled exception. Applications should check the inner exception of a PingException object to identify the problem.       The <xref:System.Net.NetworkInformation.Ping> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors. For such errors, the <xref:System.Net.NetworkInformation.Ping> class returns a <xref:System.Net.NetworkInformation.PingReply> object with the relevant <xref:System.Net.NetworkInformation.IPStatus> value set in the <xref:System.Net.NetworkInformation.PingReply.Status%2A> property.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"The <xref:System.Net.NetworkInformation.Ping> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <xref:System.Net.NetworkInformation.Ping> class threw an unhandled exception. Applications should check the inner exception of a PingException object to identify the problem.       The <xref:System.Net.NetworkInformation.Ping> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors. For such errors, the <xref:System.Net.NetworkInformation.Ping> class returns a <xref:System.Net.NetworkInformation.PingReply> object with the relevant <xref:System.Net.NetworkInformation.IPStatus> value set in the <xref:System.Net.NetworkInformation.PingReply.Status%2A> property.","pos":[0,809],"nodes":[{"content":"The &lt;xref:System.Net.NetworkInformation.Ping&gt; class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the &lt;xref:System.Net.NetworkInformation.Ping&gt; class threw an unhandled exception.","pos":[0,263],"source":"The <xref:System.Net.NetworkInformation.Ping> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <xref:System.Net.NetworkInformation.Ping> class threw an unhandled exception."},{"content":"Applications should check the inner exception of a PingException object to identify the problem.","pos":[264,360]},{"content":"The &lt;xref:System.Net.NetworkInformation.Ping&gt; class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors.","pos":[367,528],"source":"       The <xref:System.Net.NetworkInformation.Ping> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors."},{"content":"For such errors, the &lt;xref:System.Net.NetworkInformation.Ping&gt; class returns a &lt;xref:System.Net.NetworkInformation.PingReply&gt; object with the relevant &lt;xref:System.Net.NetworkInformation.IPStatus&gt; value set in the &lt;xref:System.Net.NetworkInformation.PingReply.Status%2A&gt; property.","pos":[529,809],"source":" For such errors, the <xref:System.Net.NetworkInformation.Ping> class returns a <xref:System.Net.NetworkInformation.PingReply> object with the relevant <xref:System.Net.NetworkInformation.IPStatus> value set in the <xref:System.Net.NetworkInformation.PingReply.Status%2A> property."}]}]},{"pos":[2218,2351],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Net.NetworkInformation.PingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using the specified message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class using the specified message."},{"pos":[2363,2554],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter. The <xref:System.Exception.InnerException%2A> property is set to `null`.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id=\"ph1\">`message`</ph> parameter.","pos":[0,118],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property is set to <ph id=\"ph1\">`null`</ph>.","pos":[119,191],"source":" The <xref:System.Exception.InnerException%2A> property is set to `null`."}]},{"pos":[2696,2744],"content":"A <xref:System.String> that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error.","pos":[0,48],"source":"A <xref:System.String> that describes the error."}]},{"pos":[3524,3650],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Net.NetworkInformation.PingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class with serialized data."},{"pos":[3662,3810],"content":"This constructor is called during deserialization to reconstitute a previously serialized <xref:System.Net.NetworkInformation.PingException> object.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor is called during deserialization to reconstitute a previously serialized &lt;xref:System.Net.NetworkInformation.PingException&gt; object.","pos":[0,148],"source":"This constructor is called during deserialization to reconstitute a previously serialized <xref:System.Net.NetworkInformation.PingException> object."}]},{"pos":[4112,4161],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[4266,4418],"content":"A <xref:System.Runtime.Serialization.StreamingContext> that specifies the contextual information about the source or destination for this serialization.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that specifies the contextual information about the source or destination for this serialization.","pos":[0,152],"source":"A <xref:System.Runtime.Serialization.StreamingContext> that specifies the contextual information about the source or destination for this serialization."}]},{"pos":[5020,5173],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Net.NetworkInformation.PingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using the specified message and inner exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class using the specified message and inner exception."},{"pos":[5185,5399],"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id=\"ph1\">`message`</ph> parameter, and the &lt;xref:System.Exception.InnerException%2A&gt; property with the <ph id=\"ph2\">`innerException`</ph> parameter.","needQuote":true,"needEscape":true,"extradata":"MT","source":"This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter, and the <xref:System.Exception.InnerException%2A> property with the `innerException` parameter."},{"pos":[5567,5615],"content":"A <xref:System.String> that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.String&gt; that describes the error.","pos":[0,48],"source":"A <xref:System.String> that describes the error."}]},{"pos":[5689,5737],"content":"The exception that causes the current exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that causes the current exception.","pos":[0,48]}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Net.NetworkInformation.PingException\n  id: PingException\n  children:\n  - System.Net.NetworkInformation.PingException.#ctor(System.String)\n  - System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: PingException\n  nameWithType: PingException\n  fullName: System.Net.NetworkInformation.PingException\n  type: Class\n  summary: The exception that is thrown when a <xref:System.Net.NetworkInformation.Ping.Send*> or <xref:System.Net.NetworkInformation.Ping.SendAsync*> method calls a method that throws an exception.\n  remarks: \"The <xref:System.Net.NetworkInformation.Ping> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <xref:System.Net.NetworkInformation.Ping> class threw an unhandled exception. Applications should check the inner exception of a PingException object to identify the problem.  \\n  \\n The <xref:System.Net.NetworkInformation.Ping> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors. For such errors, the <xref:System.Net.NetworkInformation.Ping> class returns a <xref:System.Net.NetworkInformation.PingReply> object with the relevant <xref:System.Net.NetworkInformation.IPStatus> value set in the <xref:System.Net.NetworkInformation.PingReply.Status%2A> property.\"\n  syntax:\n    content: 'public class PingException : InvalidOperationException'\n  inheritance:\n  - System.InvalidOperationException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Net.NetworkInformation.PingException\n  langs:\n  - csharp\n  name: PingException(String)\n  nameWithType: PingException.PingException(String)\n  fullName: System.Net.NetworkInformation.PingException.PingException(String)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Net.NetworkInformation\n  summary: Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class using the specified message.\n  remarks: This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter. The <xref:System.Exception.InnerException%2A> property is set to `null`.\n  syntax:\n    content: public PingException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error.\n  overload: System.Net.NetworkInformation.PingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Net.NetworkInformation.PingException\n  langs:\n  - csharp\n  name: PingException(SerializationInfo,StreamingContext)\n  nameWithType: PingException.PingException(SerializationInfo,StreamingContext)\n  fullName: System.Net.NetworkInformation.PingException.PingException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Net.NetworkInformation\n  summary: Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute a previously serialized <xref:System.Net.NetworkInformation.PingException> object.\n  syntax:\n    content: protected PingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);\n    parameters:\n    - id: serializationInfo\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: streamingContext\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref:System.Runtime.Serialization.StreamingContext> that specifies the contextual information about the source or destination for this serialization.\n  overload: System.Net.NetworkInformation.PingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Net.NetworkInformation.PingException\n  langs:\n  - csharp\n  name: PingException(String,Exception)\n  nameWithType: PingException.PingException(String,Exception)\n  fullName: System.Net.NetworkInformation.PingException.PingException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System\n  namespace: System.Net.NetworkInformation\n  summary: Initializes a new instance of the <xref href=\"System.Net.NetworkInformation.PingException\"></xref> class using the specified message and inner exception.\n  remarks: This constructor initializes the <xref:System.Exception.Message%2A> property with the text in the `message` parameter, and the <xref:System.Exception.InnerException%2A> property with the `innerException` parameter.\n  syntax:\n    content: public PingException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref:System.String> that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that causes the current exception.\n  overload: System.Net.NetworkInformation.PingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.InvalidOperationException\n  isExternal: false\n  name: System.InvalidOperationException\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.String)\n  parent: System.Net.NetworkInformation.PingException\n  isExternal: false\n  name: PingException(String)\n  nameWithType: PingException.PingException(String)\n  fullName: System.Net.NetworkInformation.PingException.PingException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Net.NetworkInformation.PingException\n  isExternal: false\n  name: PingException(SerializationInfo,StreamingContext)\n  nameWithType: PingException.PingException(SerializationInfo,StreamingContext)\n  fullName: System.Net.NetworkInformation.PingException.PingException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)\n  parent: System.Net.NetworkInformation.PingException\n  isExternal: false\n  name: PingException(String,Exception)\n  nameWithType: PingException.PingException(String,Exception)\n  fullName: System.Net.NetworkInformation.PingException.PingException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Net.NetworkInformation.PingException.#ctor*\n  parent: System.Net.NetworkInformation.PingException\n  isExternal: false\n  name: PingException\n  nameWithType: PingException.PingException\n"}